### ISSUE TITLE
マルコプ 大物資回収成功条件

### ISSUE THREAD

**Issue by red-null** [NOKOLat/NOKOLat_rule#3]
### 質問箇所

回収点

### 質問内容

マルコプ部門での救援物資（大）の回収成功とは、どの状態を指しますか。
ex.)物資が機体に引かれて宙に浮くこと
また、回収後、運搬途中で落としたら回収失敗になりますか。

**Comment by SatoshiRC** [comment]
機体が把持もしくは吊り下げることにより救援物資（大）が接地していない状態が維持されていると認められるときに回収成功とします．回収成功と認められた後に救援物資（大）が落下しても回収点は与えられます．
